version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'java-postgres32432'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 18092005
      POSTGRES_DB: java